name: Run Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install Dependencies
      run: |
        pip install black mypy pydantic pyflakes pytest ruff

    - name: Execute test.sh
      run: |
        chmod +x ./test.sh
        ./test.sh
